### ISSUE TITLE
AP database: RPostgreSQL returns local time when selecting UTC

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/cardatdbtools#6]
Using this query, I noticed that my conversion from UTC to local time returned the wrong time in R, but correct using PGADMIN

```
SELECT station, state, year, date, hour, date_time_utc, extract(month from date) as mm,
  date_time_utc + interval '10 hour' as local_time,
  variable, value as o3, units, measurement_method, time_basis
FROM air_pollution_monitors.ap_monitor_data_master
where variable = 'o3'
 and state in ('NSW', 'QLD', 'SA', 'VIC', 'ACT')
 and time_basis = '1hr_av'
```

**Comment by ivanhanigan** [comment]
@cassandrayuen

**Comment by ivanhanigan** [comment]
THis SQL may not actually work anyway @cassandrayuen

**Comment by cassandrayuen** [comment]
The SQL works as intended in both R and pgAdmin. The date_time_utc field has timezone attached and is stored as UTC timestamp in the database, but will convert to local time of the client.

Thus for pgAdmin, date_time_local is literally 10 hours forward of date_time_utc but still has UTC timezone:
![image](https://github.com/cardat/cardatdbtools/assets/97654691/ed0d901e-fa65-4962-a3f9-9d815cf2ee28)

But in R, date_time_local is again 10 hours forward of date_time_utc but both fields have been converted to display in R's Sys.timezone:
![image](https://github.com/cardat/cardatdbtools/assets/97654691/003157bc-936b-4d92-914e-9f9e9d519c90)
More evident when you show the date_time_utc vector alone (POSIXct type with timezone:
![image](https://github.com/cardat/cardatdbtools/assets/97654691/3b19ce20-48e7-4446-b447-39caeda1a4d9)

I think if working in pgAdmin, use `date_time_utc AT TIME ZONE INTERVAL '+10:00' as local_time` which will return a timestamp without timezone. 

Otherwise if in R, just retrieve the date_time_utc/date/hour fields and do the timezone/timestamp manipulations in R. E.g.  `attr(dat$date_time_utc, "tzone") <- "UTC"` to make it display the time in UTC timezone. It's important to note that a lot of functions (when converting the POSIXct type) has a tz argument, which affects output. For example, the strftime function uses R's local timezone as default, whereas the as.Date function uses UTC as default. Use the tz argument to ensure output in the timezone you want.
(Alternatively try tools in `lubridate` and/or `clock` packages)
